USE hexa_db;

DROP TABLE IF EXISTS products;

CREATE TABLE products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image VARCHAR(255) NOT NULL
);

INSERT INTO products (name, description, price, image) VALUES
('Hexa Classic Tee', 'Soft cotton classic fit tee.', 19.99, '/assets/t-1.jpg'),
('Veritas Strength Tee', 'Strength themed cotton tee.', 22.99, '/assets/t-2.jpg'),
('Charole Noir Tee', 'Dark black style tee.', 18.99, '/assets/t-3.jpg'),
('Elion Focus Tee', 'Focus design everyday tee.', 24.99, '/assets/t-4.jpg'),
('Divinus Path Tee', 'Path graphic cotton tee.', 20.99, '/assets/t5.jpg'),
('Urban Street Tee', 'Streetwear urban fit.', 17.99, '/assets/t-6.jpg'),
('Vintage Graphic Tee', 'Retro graphic print tee.', 25.99, '/assets/t-7.jpg'),
('Minimalist White Tee', 'Clean minimalist design.', 16.99, '/assets/t-8.jpg'),
('Premium Cotton Tee', 'High quality cotton.', 28.99, '/assets/t - 9.jpg'),
('Fitness Gym Tee', 'Gym ready performance tee.', 21.99, '/assets/t -10.jpg'),
('Graphic Bold Tee', 'Bold graphics tee.', 19.49, '/assets/t-12.jpg'),
('Casual Daily Tee', 'Casual everyday wear.', 15.99, '/assets/logo.png'),
('Street Art Tee', 'Art inspired street tee.', 23.99, '/assets/avatar.jpg'),
('Eco Friendly Tee', 'Sustainable cotton tee.', 26.99, '/assets/t-1.jpg'),
('Summer Light Tee', 'Lightweight summer tee.', 18.49, '/assets/t-2.jpg'),
('Winter Heavy Tee', 'Heavy fabric winter tee.', 29.99, '/assets/t-3.jpg'),
('Logo Brand Tee', 'Brand logo tee.', 20.49, '/assets/logo.png'),
('Funny Print Tee', 'Humorous print tee.', 17.49, '/assets/t5.jpg'),
('Sport Performance Tee', 'Performance sport tee.', 24.49, '/assets/t-4.jpg'),
('Elegant Slim Fit Tee', 'Slim fit elegant.', 22.49, '/assets/t-6.jpg'),
('Oversize Loose Tee', 'Oversize casual.', 16.49, '/assets/t-7.jpg'),
('V Neck Tee', 'V-neck style tee.', 21.49, '/assets/t-8.jpg'),
('Polo Shirt Tee', 'Polo collar tee.', 27.99, '/assets/t - 9.jpg'),
('Long Sleeve Tee', 'Long sleeve cotton.', 25.49, '/assets/t -10.jpg'),
('Short Sleeve Tee', 'Short sleeve basic.', 14.99, '/assets/t-12.jpg'),
('Printed Pattern Tee', 'Pattern print tee.', 19.49, '/assets/avatar.jpg'),
('Solid Color Tee', 'Solid black tee.', 18.99, '/assets/t-1.jpg'),
('Striped Tee', 'Striped pattern tee.', 23.49, '/assets/t-2.jpg'),
('Camouflage Tee', 'Camouflage print tee.', 26.49, '/assets/t-3.jpg'),
('Floral Tee', 'Floral design tee.', 20.99, '/assets/t-4.jpg'),
('Geometric Tee', 'Geometric pattern tee.', 22.99, '/assets/t5.jpg'),
('Abstract Art Tee', 'Abstract art print.', 24.99, '/assets/t-6.jpg'),
('Music Band Tee', 'Band logo tee.', 17.99, '/assets/t-7.jpg'),
('Movie Quote Tee', 'Movie quote print.', 21.99, '/assets/t-8.jpg'),
('Gaming Tee', 'Gamer theme tee.', 25.99, '/assets/t - 9.jpg'),
('Tech Logo Tee', 'Tech brand tee.', 19.99, '/assets/t -10.jpg'),
('Nature Scene Tee', 'Nature inspired.', 28.99, '/assets/t-12.jpg'),
('Animal Print Tee', 'Animal motif tee.', 16.99, '/assets/logo.png'),
('Food Theme Tee', 'Food graphic tee.', 20.49, '/assets/avatar.jpg'),
('Travel Adventure Tee', 'Adventure travel.', 23.99, '/assets/t-1.jpg'),
('Motivational Quote Tee', 'Motivational text.', 18.49, '/assets/t-2.jpg'),
('Luxury Brand Tee', 'Luxury style tee.', 32.99, '/assets/t-3.jpg'),
('Budget Basic Tee', 'Basic affordable tee.', 12.99, '/assets/t-4.jpg'),
('Organic Cotton Tee', 'Organic fabric tee.', 27.49, '/assets/t5.jpg'),
('Quick Dry Tee', 'Quick dry sport tee.', 24.49, '/assets/t-6.jpg'),
('Thermal Tee', 'Thermal lined tee.', 29.49, '/assets/t-7.jpg'),
('Mesh Breathable Tee', 'Breathable mesh tee.', 22.49, '/assets/t-8.jpg'),
('Hoodie Tee', 'Hooded t-shirt.', 30.99, '/assets/t - 9.jpg'),
('Pocket Tee', 'Pocket detail tee.', 19.49, '/assets/t -10.jpg'),
('Round Neck Tee', 'Round neck classic.', 15.49, '/assets/t-12.jpg'),
('Crew Neck Tee', 'Crew neck fit.', 21.49, '/assets/logo.png'),
('High Low Hem Tee', 'High low hem.', 25.49, '/assets/avatar.jpg'),
('Ringer Tee', 'Ringer edge tee.', 18.99, '/assets/t-1.jpg'),
('Henley Tee', 'Henley button tee.', 26.99, '/assets/t-2.jpg'),
('Tank Top Tee', 'Sleeveless tank.', 14.49, '/assets/t-3.jpg'),
('Crop Tee', 'Crop top tee.', 17.49, '/assets/t-4.jpg');

